[build]
  # Comando para construir seu projeto Nest.js
  command = "npm run build"
  
  # Pasta onde o build do Nest.js é gerado
  publish = "dist"
  
  # Pasta onde a sua função serverless compilada estará
  functions = "dist/src"

[build.environment]
  # Variáveis de ambiente para o build
  NODE_VERSION = "18"

[[redirects]]
  # Redireciona todas as requisições para a nossa função serverless
  from = "/*"
  to = "/.netlify/functions/main.serverless"
  status = 200